### ISSUE TITLE
Do Mockups For The Squad Likish Compass

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#103]
Create mockups, maybe even multual, for the squad likish compass.

**Comment by filipbasara** [comment]
First iteration has been pushed to master. Awaiting feedback @Hoegnison @jokoho48

**Comment by jokoho48** [comment]
i like the compass with  the white background but i would like it more if we fade the edges like we did in the Notification. And the Units that are around you the icons from then are missing like in the squad compass

**Comment by simon84** [comment]
I like the following: `PRA3-Compass_white_transparent_background.png`
In my opinion it fits very good to all other arma hud elements.

**Comment by Hoegnison** [comment]
I feel the same like badguy. It fits perfectly. Good job mitsu! I guess we are going to take a closer look on tuesday during the meeting.

**Comment by jokoho48** [comment]
i like the newst Version with the Icons but i think that the normal Icons from the normal units are too big

**Comment by filipbasara** [comment]
@jokoho48 I agree, the Icons definitely could use some work. As of now they're not really consistent when compared to the rest. Also I need to figure out how to make the UI look less bland. The amount of drop shadow used is too damn high :smile:

**Comment by filipbasara** [comment]
Updated with new icons and new waypoint markers

**Comment by simon84** [comment]
Is it possible to create a layout which is more compact? Especially in height?

**Comment by jokoho48** [comment]
and think about the squad list: https://community.bistudio.com/wikidata/images/c/c6/Guide01x-1-.jpg

**Comment by filipbasara** [comment]
@simon84 yes it's possible. Will revisit the concept with your suggestion in mind though I'm not sure how good it'll look with a very squeezed compass. Could resize the icons and make them smaller, for instance.
@jokoho48 True, that's going to be an issue with the current width. What's the maximum count for Squad members? Would like to know so I can adjust.

**Comment by jokoho48** [comment]
10 on one side if you have more than you get a secound page

**Comment by filipbasara** [comment]
Rework imminent. A more compact, streamlined and visually appealing version will be updloaded soon.
