### ISSUE TITLE
Media Rollout Templates

### ISSUE THREAD

**Issue by Bluedrake42** [drakelinglabs/projectrealityarma3#107]
We need media rollout templates for when we release the first version of the mission. This is something I expect Mitsu to handle primarily, as he seems to be the best suited for the job.

We need screenshot overlays, feature showcases, feature lists, in-game footage for trailers, logos, intros, etc. I'd like to have something that is both informative and professional upon release.

**Comment by filipbasara** [comment]
@Bluedrake42 
I can supply anything but video content. I don't own any proper video editing software at this point (though I'm looking to subscribe to After Effects again) and I generally am not experienced enough to create professional video content. I will give it a shot nonetheless, also out of personal interest.
