### ISSUE TITLE
Think about side switch restriction

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#112]

**Comment by Hoegnison** [comment]
I guess that is a good idea. Maybe you can not switch when the team has +3 players?

**Comment by simon84** [comment]
Maybe we should consider a relative measure. E.g. 10 percent of the total player count.

**Comment by netfusion** [comment]
To make it possible for small groups to join a side as one, I suggest a absolut number.
In my opinion the difference in the amount of players on each side should not be more than 5.

**Comment by Hoegnison** [comment]
I guess we have some ideas, we can talk about in the upcoming sprintmeeting :)
I will close the issue and we are going to talk about taht in detail on saturday.
