### ISSUE TITLE
Limit Length of Custom Squad Name

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#129]

**Comment by netfusion** [comment]
14 is the maximal amount of 'w' characters i can type without overlapping the squad type.
This may change with other interface size settings!

**Comment by jokoho48** [comment]
i think that we somehow should show the player that the he only can type 14 chars

**Comment by jokoho48** [comment]
just show a hint if the player have more then 14 chars in the Text box? and remove the last

**Comment by jokoho48** [comment]
Final Visual Enhancement was made by @simon84 and merged in master
