### ISSUE TITLE
Need the ability to pay test easily

### ISSUE THREAD

**Issue by onedigita** [drakelinglabs/projectrealityarma3#136]
Sorry guys Ive tried to follow the method described to play test but I cannot get it working.  I cant describe how excited I am for this

**Comment by Hoegnison** [comment]
Cheers, you have to download the project, pack the serverside scripts in a pbo and load the mission. 
We will do public playtests in the future though, so please be patient :) 
For future feature requests please follow these rules and do not open issues on your own.
https://github.com/drakelinglabs/projectrealityarma3/wiki/How-to-request-a-feature
We have to keep track of the project and this is our main management tool.
