### ISSUE TITLE
Deploy FOB Function

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#139]
Create logic for deploying a fob.

**Comment by netfusion** [comment]
we should do #178 first

**Comment by jokoho48** [comment]
yes all is next milestone currently not in our focus

**Comment by netfusion** [comment]
I implemented the possibility to create a FOB.
Currently we need more detailed documentation of:

- [ ] Restriction for placing an FOB
- [ ] How can a FOB be destroyed

At the moment it is not possible to destroy a FOB
