### ISSUE TITLE
Think about showing Uncon Status in UnitTracker

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#142]

**Comment by Hoegnison** [comment]
I think that is a good idea. Maybe just for medics? 
Could be usefull to know if a medic is uncon aswell. What do you guys think?

**Comment by Hoegnison** [comment]
Sprintmeeting:
On Map: If medic uncon status for whole team. Else uncon status for squad.
compass: If medic uncon status in compass. Else nothing.
