### ISSUE TITLE
Garbage collector

### ISSUE THREAD

**Issue by netfusion** [drakelinglabs/projectrealityarma3#144]
Write an GC which handles corpses, empty smoke shells and empty groups.

**Comment by jokoho48** [comment]
fixed with https://github.com/drakelinglabs/projectrealityarma3/commit/54053ca23f50250779a32e11a5ceb8836fbef418 and https://github.com/drakelinglabs/projectrealityarma3/commit/6dd065837ad956c1db57aed780c10803ad07b000
