### ISSUE TITLE
Work On Localization

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#148]
Rewrite some ingame messages and kill ze german english.

**Comment by jokoho48** [comment]
- [ ] Mission Configs

- [ ] Deployment >> fn_clientInitDeplayment.sqf >> L21
- [ ] Deployment >> fn_placeRally.sqf >> L42

- [ ] Logistic >> fn_postInit.sqf >> L67 && L82 && L92 && L110 && L148 && L226 && L238

- [ ] Nametags>> fn_clientInit.sqf >> L71

- [ ] RespawnUI >> fn_clientInitRespawn.sqf >> L129 && L139 && L145 && L153
- [ ] RespawnUI >> fn_clientInitSquad.sqf >> L117 && L158 & L164

- [ ] Revive >> HitEffects >> fn_clientInitHitEffects.sqf >> L57
- [ ] Revive >> HitEffects >> fn_clientInitHitEffects.sqf >> L57
- [ ] Revive >> HitEffects >> fn_unconscious.sqf >> L126-L127

- [ ] Revive >> Treatments >> fn_revive.sqf >> L64 && L68
- [ ] Revive >> Treatments >> fn_heal.sqf >> L109
- [ ] Revive >> Treatments >> fn_clientInitTreatmentsUI.sqf >> L49-L53 && L68-L69 && L166-L172
- [ ] Revive >> Treatments >> fn_bandage.sqf >> L74

- [ ] Sector >> fn_init.sqf >> L90-L108
- [ ] VehicleRespawn >> fn_clientInit.sqf >> L21
