### ISSUE TITLE
Inventory Restriction based on Role selection

### ISSUE THREAD

**Issue by simon84** [drakelinglabs/projectrealityarma3#17]
We need an inventory restriction based on the selected role. Otherwise, e.g. an at player could equip his squad with an at weapon, by multiple role selection/rearming, and giving his weapon to his squad mates.

**Comment by Hoegnison** [comment]
I am not sure if this is wanted. Remember what we said in the meeting. Let ArmA be ArmA. But I will add a discussion label on this and move it to the backlog. I guess we have enough time to sort it out first :)
PS: I like the idea, though!

**Comment by simon84** [comment]
Of Course, the idea is not to disable the inventory at all. But the problem is, that players are able to bypass the role restriction System. We can have a sniper/at-pilot and so on. And i don't think, that this is wanted.

**Comment by Hoegnison** [comment]
Absolutly right. I will talk about it with BD and he will give us further feedback about it. 
But I am sure it is going to make the gameplay better.
