### ISSUE TITLE
Player was killed messages on JIP

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#191]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ When server has kill messages turned on (Which it shouldn't anyway imo) you get kill messages for the scripted respawns as well. forceRespawn command can be used to circumvent this.

### Steps to reproduce:
+ Join mission. See 'Playername was killed' in systemchat

### Where did the issue occur?
+ Dedi MP

**Comment by Hoegnison** [comment]
Turn off kill messages on the serverside. Rework the codepart for killing players after JIP

**Comment by jokoho48** [comment]
the Server side thing is fixed the JIP thing i can not reproduce
