### ISSUE TITLE
Squad marker mouseover shows members of player's squad instead of target squad

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#194]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ When you mouseover the squad marker of another squad, it does show the name and type of that squad, but it'll show the members of your own squad in the list below it. 

### Steps to reproduce:
+ Join squad A
+ Mouse over squad B marker

### Where did the issue occur?
+ Dedi MP

**Comment by Adanteh** [comment]
![20160604211419_1](https://cloud.githubusercontent.com/assets/1355127/15801883/32625556-2aa3-11e6-9f0b-11d40b8138f0.jpg)

**Comment by simon84** [comment]
fixed
