### ISSUE TITLE
When unconscious, closing map doesn't work with M

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#196]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ When you go unconscious, you  can open the map just fine with M, but Esc has to be used to close the map again, where the expected behaviour is that you can also close the map again with M.

### Steps to reproduce:
+ Go unconscious
+ Press M to open map
+ Press M to close map (Doesn't work)
+ Press Esc to close map (Does work)

### Where did the issue occur?
+ Dedi MP

**Comment by simon84** [comment]
fixed
