### ISSUE TITLE
No player markers on GPS

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#197]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ Player markers are not shown on the GPS at all. Need to have the drawIcon work on GPS map control as well. 90% sure that it's just not implemented yet. 
`((uiNamespace getVariable "RscMiniMap") displayCtrl 101) `

### Steps to reproduce:
+ Get a GPS
+ Open GPS (Ctrl+M)
+ See no player markers on it)

### Where did the issue occur?
+ Dedi MP

**Comment by simon84** [comment]
implemented in 6495abf99d7a0c9c1e9365406bd6d8526b89642d
