### ISSUE TITLE
Short gamefreeze on squad marker mouse over / mouse out

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#198]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ After the mission was running for a while, doing mouse over on squad markers would freeze the game for a couple seconds. The same would happen on mouse out. 

### Steps to reproduce:
+ Play mission for a little
+ Mouse over squad marker
+ Move mouse way from squad marker

### Where did the issue occur?
+ Dedi MP

**Comment by simon84** [comment]
Can't reproduce. Could be a problem with the empty groups. We keep an eye on this.

**Comment by simon84** [comment]
Should be fixed now
