### ISSUE TITLE
VoN disables after the respawn into unconscious state after couple seconds

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#199]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ Not sure if intentional that it's disabled at all, but when you go incapped you can't talk because you're dead (to the engine), then on the unconscious respawn you can talk about for about 5 seconds, after which your VoN disables again. Seems funky

### Steps to reproduce:
+ Sing Russian anthem on VoN
+ Go incap (VoN stops)
+ Respawn in unconscious (VoN works again)
+ Wait couple seconds (VoN stops)

### Where did the issue occur?
+ Dedi MP

**Comment by jokoho48** [comment]
50% of the issue is Related to our BlockUserInput.

**Comment by netfusion** [comment]
We need to rewrite the RespawnUI dialog as a display to allow arma capturing the PTT Key while its open.
This need a lot of changes so we can not do it in 0.6 milestone.
