### ISSUE TITLE
Search For New Icons

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#20]
Searching for new icons in the native arma addons, report back to the ui guys.

**Comment by simon84** [comment]
First Icons:
pbo_f_data.pbo
a3\ui_f\data\
 - IGUI\Cfg\Cursers\getin_ca.paa //Deployment
 - IGUI\Cfg\Actions\reammo_ca.paa //Loadouts
 - IGUI\Cfg\Actions\gear_ca.paa //Loadouts
 - gui\Rsc\RscDisplayArcadeMap\icon_toolbox_groups_ca.paa //Squad

**Comment by Hoegnison** [comment]
Ich hätte noch folgende Icons:

ui_f_data\gui\Rsc\RscDisplayGear\igui_gear_filter_2_ca.paa  //Loadouts
ui_f_data\gui\Rsc\RscDisplayGear\igui_gear_filter_1_ca.paa  //Loadouts
ui_f_data\gui\Rsc\RscDisplayGear\ui_gear_uniform_gs.paa  //Loadouts
ui_f_data\gui\cfg\Hints\firemode_ca.paa //Loadouts
ui_f_data\gui\cfg\Hints\gear_ca.paa //Loadouts

ui_f_data\gui\Rsc\RscDisplayEGSpectator\UnitIcon_ca.paa  //Deploy
ui_f_data\gui\RscCommon\RscTree\hiddentexture_ca.paa //Deploy
ui_f_data\gui\cfg\Hints\checkpoints_ca.paa //Deploy
ui_f_data\gui\cfg\CommunicationMenu\transport_ca.paa


ui_f_data\gui\Rsc\RscDisplayMultiplayerSetup\disabledai_ca.paa //Squad
ui_f_data\gui\cfg\Hints\basicstances_ca.paa //Squad
ui_f_data\gui\cfg\Hints\commanding_ca.paa //Squad
