### ISSUE TITLE
Sometimes switching squads doesn't show any roles

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#200]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ After leaving my own created squad and joining another, it would not show me in the list of squad members and would also not show any roles within said squad.

### Steps to reproduce:
+ Join squad A. 
+ Play for a little.
+ Join squad B
+ See an empty role list
+ Name only shows up in said squad after waiting a little

### Where did the issue occur?
+ Dedi MP

![20160604221133_1](https://cloud.githubusercontent.com/assets/1355127/15801952/12119e22-2aa5-11e6-9553-7caeec2e9397.jpg)

**Comment by netfusion** [comment]
probably fixed with #176
