### ISSUE TITLE
Abort button on Esc Menu on Respawn screen doesn't work

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#201]
### ArmA3 Version:
- 1.60
### PRA3 Version:
- 0.5.0.215
### Description:
- When you're dead, pressing Esc to get to the menu works fine, but pressing Abort doesn't do anything. It should make you leave the mission
### Steps to reproduce:
- Die!!
- Press Esc
- Click Abort button (Nothing happens)
### Where did the issue occur?
- Dedi MP

![20160604221332_1](https://cloud.githubusercontent.com/assets/1355127/15801955/2cb72788-2aa5-11e6-8749-d859d2fb83c4.jpg)

**Comment by simon84** [comment]
Could not reproduce this issue. Need more info!

**Comment by Adanteh** [comment]
Will have to check another time. It was quite late in the playtest and seemed to work fine before. I think it was when I switched squads (Not sure if related at all)
