### ISSUE TITLE
While bandaging someone it shows "You are being healed" on yourself

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#202]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ Go to incap guy and start bandaging. After a couple of seconds it starts showing "You are being healed" on yourself. (No one was healing me for the record)

### Steps to reproduce:
+ Bandage incap guyh
+ After a couple seconds "You are being healed!" shows up
+ Stop bandaging and it removes the message

### Where did the issue occur?
+ Dedi MP

![20160604220036_1](https://cloud.githubusercontent.com/assets/1355127/15801983/f1550312-2aa5-11e6-890f-3a9aede91b1d.jpg)

**Comment by simon84** [comment]
Can't reproduce, But we will keep an eye on it.

**Comment by simon84** [comment]
obsolete due to the new revive system
