### ISSUE TITLE
Fix PRT messages

### ISSUE THREAD

**Issue by netfusion** [drakelinglabs/projectrealityarma3#203]
- [x] `Attempt to override final function - pra3_module_fnc_function`
- [x] `A nil object passed as a target to RemoteExec(Call) 'pra3_core_fnc_localevent'`
- [x] `WARNING: Function 'name' - Player is dead`

**Comment by jokoho48** [comment]
1. should be fix with the #220 
2. should be already fixed.
3. we can't fix that. that is a BIS fault
