### ISSUE TITLE
Squad marker mouseover shows no max squad member count

### ISSUE THREAD

**Issue by netfusion** [drakelinglabs/projectrealityarma3#205]
### ArmA3 Version:
+ 1.60

### PRA3 Version:
+ 0.5.0.215

### Description:
+ When you mouseover the squad marker of another squad, it does not show the maximum member count of that squad.

### Steps to reproduce:
+ Join squad A
+ Mouse over squad B marker

### Where did the issue occur?
+ Dedi MP

**Comment by netfusion** [comment]
May be related to #194

**Comment by simon84** [comment]
Should be fixed in #160
