### ISSUE TITLE
Rework Crew restriction On Vehicles

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#209]
Rework the restriction system so it gets more stable.

**Comment by netfusion** [comment]
Need new idea here cause my old one is not possible to implement...
Anyone expected issues with the current one in the latest playtests?

**Comment by simon84** [comment]
Possible solution: Override Vanilla action with CLib_fnc_overrideAction

**Comment by netfusion** [comment]
almost done....only FFV slot should be usable without driver

**Comment by netfusion** [comment]
Not possible to figure out which specific turret the player wants to board.
This makes it impossible to check the config for FFV seats.

**Comment by jokoho48** [comment]
but we must find a way to detect this befor we close/test this.

**Comment by Montiemedia** [comment]
If you are Crewmember, you can join as Helo Gunner an co-pilot. But the Heli Crew members are different to ground crew member. Create another Crew Group for helicopter Crews. If you are an Heli Pilot, you can´t join the gunner oder crew position.

**Comment by netfusion** [comment]
@Montiemedia This is intended behaviour. Create a discussion or feature request and vote for a change.

**Comment by TomNedry** [comment]
Behaviour is: a) "Tank" and "Wheeled APC": Crew-kit mandatory for driver, gunner and commander. Gunner and commander can be manned while a player is on the driver position only. Gunner and commander stay on position while the driver gets out.

b) "Air vehicles": Pilot-kit is mandatory for pilot position. Crew-kit is mandatory for co-pilot, gunner and "passenger window left (right)".  Co-pilot, gunner and "passenger window left (right)" can be manned while a player is on the pilot position only.

After consulting NetFusion and jokoho48 thats intended...

Tested & Good!
