### ISSUE TITLE
Unconscious function saves killer vehicle rather than crew of killer vehicle

### ISSUE THREAD

**Issue by Adanteh** [drakelinglabs/projectrealityarma3#219]
### Description:
- In Revive\HitEffects\fn_unconscious.sqf there's a potential problem. When a unit goes unconscious the killer is saved, however this is the VEHICLE(!!) that did the killing. Now when someone dies after being unconscious the only info you have is said vehicle. 

The problem comes from trying to use it for score systems or similar, where Player A and Player B might be in the vehicle when incapping a unit C, if unit A and unit B leave the vehicle before unit C dies, then you don't have any info on the fact that it was unit A and unit B did the killing. 
### Fix:
- Save the crew of the vehicle rather than the vehicle itself

Here's what i used http://pastebin.com/tvLVQ3cx

**Comment by jokoho48** [comment]
this module got a rework in the last milestone
