### ISSUE TITLE
Do Mockups For The Next UI Iteration

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#22]
Do some mockups for the ui, including icons and the persistent part of the ui.

**Comment by Hoegnison** [comment]
Ich denke damit bist du durch oder BadGuy?

**Comment by simon84** [comment]
Ich warte noch auf Feedback. Ich habe noch eine Idee für Überarbeitung. Wird aber nur was für den 2. Prototypen. Vielleicht in den backlog.

**Comment by filipbasara** [comment]
Do you need any help with it? I'm a Web+UI Designer and I could offer some assistance.

**Comment by Hoegnison** [comment]
@filipbasara Pls contact me on discord. You can find me as a product manager on the Drakelings discord. 
Cheers.
