### ISSUE TITLE
Squad lead position not available when vacant

### ISSUE THREAD

**Issue by WarJebus** [drakelinglabs/projectrealityarma3#243]
### ArmA3 Version:

Launcher version: 1.5.136470

Game version: 1.60.136470

Branch: main / beta branch not specified
### Mods:

None.
### Description:

When squad lead disconnects or switches squad, the squad lead position was not visible to existing squad members who entered the respawn menu for some time.
### Where did the issue occur?

Project Reality Arma 3 Internal Test Server

**Comment by WarJebus** [comment]
I will also add that there was a fair amount of server stutter when this happened.

**Comment by filipbasara** [comment]
Can confirm. I was said Squad Leader. Possibly related to the issue that SL can't promote other Squad Members to Squad Leader

**Comment by filipbasara** [comment]
Possibly linked to issues #245 and #246

**Comment by jokoho48** [comment]
need Testing to Confirm that this is still a bug/allready fixed

**Comment by pwilkutowski** [comment]
QA started

**Comment by pwilkutowski** [comment]
Cannon reproduce on current build / version
Tested with 2 squad members on the server.
