### ISSUE TITLE
Sometimes weird squadmembers show up

### ISSUE THREAD

**Issue by litrax** [drakelinglabs/projectrealityarma3#247]
### ArmA3 Version:
+ Launcher version: 1.5.136470
+ Game version: 1.60.136470
+ Branch: stable

### PRA3 Version:
+ 0.6

### Mods:
+ none

### Description:
Sometimes random squadmembers show up in the ui.
At no time there were AI- or whatsoever squadmates named "Baker" in our squad.

But see this screenshot:
![Weird squadmembers](http://i.imgur.com/Tpl2wfg.jpg)
http://i.imgur.com/Tpl2wfg.jpg

Two squadmembers named "Baker" !? That's weird...

A minute later, after a short switch to my desktop to make some TS-Settings, the faboulus "Baker-Twins" disappeared somehow !?

### Steps to reproduce:
+ Just respawn at the main base

### Where did the issue occur?
+ 2nd Playtest

**Comment by netfusion** [comment]
my be fixed with 882f0e3a0ca0825b6b3a153c44aed1caa09081bf
