### ISSUE TITLE
Player is dragged around with crate if in inventory of that

### ISSUE THREAD

**Issue by litrax** [drakelinglabs/projectrealityarma3#248]
### ArmA3 Version:
+ Launcher version: 1.5.136470
+ Game version: 1.60.136470
+ Branch: stable

### PRA3 Version:
+ 0.6

### Mods:
+ none

### Description:
The player was dragged around with an ammocrate if he is in the inventory of that crate and another player is dragging it around. After some time the player falls unconcious.

As seen in this video:
https://youtu.be/2Z9U9Tx6VKc?t=1h14m7s

### Steps to reproduce:
+ Player 1 gets in the inventory of a ammocrate
+ Player 2 drags around the crate
+ Player 1 gets dragged around with the crate
+ Player 1 gets hurt
+ Player 1 gets unconcious

### Where did the issue occur?
+ 2nd Playtest

**Comment by litrax** [comment]
Did look at the video evidence again. Perhaps it was the other crate that hit the player several times and made him unconcious!? How do you think?

**Comment by jokoho48** [comment]
yes that is the issue that we cant fix currently.
