### ISSUE TITLE
Exploding Vehicles Does Not Hurt Passengers.

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#254]
If a vehicle explodes the passengers are not hurt.

**Comment by jokoho48** [comment]
move back until we have decided how we will handle the Damage system

**Comment by jokoho48** [comment]
need testing after the Rewrite.

**Comment by pwilkutowski** [comment]
QA started, will try to check this but may need additional QA's

**Comment by TomNedry** [comment]
Tested & good!

The test was a side effect of testing for reproducing #416. Exploding UH-80 killed player.
