### ISSUE TITLE
How to prevent AT/Sniper but not restricting gear.

### ISSUE THREAD

**Issue by simon84** [drakelinglabs/projectrealityarma3#27]
Here are some Ideas which I had in mind after our discussion on TS how to handle role restrictions

I like the idea of not restricting items in the game. The game runs much more fluent without a restriction. But we need a bonus/malus system, to prevent persistent, unrealistic loadouts. This system should be natural to the player like the BI stamina system.

First of all we need some term descriptions.

**Role:** The player can select a role at respawn or on special points in the game (Main Base etc.). This role is persistent unless he select a different role in the role selection ui. 

**Kit:** The kit is the default loadout of a role including the role specific item (MedKit, AT launcher, sniper etc). Every Player, independent on its role, can use kit items of other roles.

**Role specific item:** Every Kit has one _role specific item_. Only player with the appropriate _role_ can use this item without a malus.

**Malus:** If a player uses a role specific item which is not fitting his role, he will get a certain malus. This could be an decreased stamina,m or increased weapon sway etc. 

**Special abilities:** some roles (not kits) has special abilities. E.g. The team leader is able to spawn a rally point. A Pilot can fly aircrafts etc.

### Examples:

**Rifleman** _Default Role_
Role specific item: none
Malus for other players using role specific item: none
Special abilities: none

**Squad leader** _only selectable by squad leader_
Role specific item: none
Malus for other players using role specific item: none
Special abilities: 
- radio to communicate with the hole team
- Can spawn squad rally points

**Medic**
Role specific item: MedKit
Malus for other players using role specific item: none
Special abilities: 
- Can perform healing/reviving faster
- Can perform a 100% heal

**AT**
Role specific item: AT launcher
Malus for other players using role specific item: decreased stamina, maybe increased weapon sway on primary weapon. 
Special abilities: none

**Marksman**
Role specific item: better scope
Malus for other players using role specific item: increased weapon sway on weapon with scope (due to higher weight :))
Special abilities: none

**Sniper**
Role specific item: sniper rifle
Malus for other players using role specific item: increased weapon sway on sniper
Special abilities: none

**Grenadier**
Role specific item: underslung grenade launcher
Malus for other players using role specific item: increased weapon sway with grenade launcher
Special abilities: none

**Pilot**
Role specific item: none
Malus for other players using role specific item: none
Special abilities: 
- Is able to fly aircrafts

---

Hopefully you are able to get my point. With this system we can restrict the role selection in ui according to the number of players in squad/team without the restriction of special items in the battlefield.

This thread was written on a smartphone. Please excuse misspelling.

**Comment by Hoegnison** [comment]
I think these idead are great. A basement where we can build a solid discussion on!
