### ISSUE TITLE
"Highlight" letters on CompassUI

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#271]

**Comment by netfusion** [comment]
I increased the size of the letters. Maybe we could reduce the size of the numbers too.

**Comment by TomNedry** [comment]
"Letters" are now a bit bigger, but it's not really "highlighted". It may help to reduce the compass numbers to half the height of the "letters".

**Comment by TomNedry** [comment]
Netfusion has reduced size of numbers. Tested & good.
