### ISSUE TITLE
Revive Rework Discussion

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#277]

**Comment by jokoho48** [comment]
PRA3_Revive Module Rework;

The New Vanilla revive System bring us new Animations, Script Commands and General UI Data.
The Vanilla Revive System is not useable in the Scope of PRA3 because:
- The Complet Function run not engine side its based on scripts and scheduled Env.
- The Complet System use Obsolet and Slow commands like VAR = VAR + [var1] massivly without reason.
- The Hold Down Actions is also not Engine Based. it have the same issues as the Revive Module have. it also have the issue that it run every code that you pass to the function get executed in a scheduled Env.
- We as PRA3 can only use the new/updated Script commands that the update bring.


Current System with new Commands for Uncon/Ragdoll/Animations/Resturcture:
Pros: 
- interruptible actions(self Stoped)
- Old Known system from PR rebuildable

Cons:
- No Animations for Limbing
- No good Animation for Healing
- Body Replacing after 3sec

TODOs:
- Rewrite Uncon
- Rewrite Ragdoll/dead Animation
- Write new KeyDown EH Based on Vanilla Data

Vanilla Damage Oriented System(Vanilla Damage with Handle Damage Maxed to 0.95 and setIncap):
Pros: 
- No Body Replacing
- Healing Animation
- Healing over the Vanilla Action

Cons
- No interruptible Healing actions(if the Animation Play you can not stop)
- No Revive Animation
- 2 Different Actions are required to heal a person

TODOs.
- Complet Rewrite
- Write new KeyDown EH Based on Vanilla Data

conclusion:
We can Profied of the new Vanilla System and new Data we get with the Update. But we can not use the Vanilla system and need to rewrite every system if we want to stay with our schedular idea.

**Comment by filipbasara** [comment]
Great idea. I like it a lot.

**Comment by Hoegnison** [comment]
I think we should go for the system that fits our gameplay type. I am not sure if the vanilla damage system fulfills this requirement. Would prefere another meeting to talk about this. Maybe during the next sprintmeeting? Or during the playtest iteration?

**Comment by jokoho48** [comment]
TODO:
- [ ] add Dragging/ Carry Uncon Players Feature
- [ ] add Pull out of Vehicle Feature

**Comment by jokoho48** [comment]
rewrite Finished
