### ISSUE TITLE
Game crash at inventory handling with container

### ISSUE THREAD

**Issue by litrax** [drakelinglabs/projectrealityarma3#290]
### ArmA3 Version:
+ 

### PRA3 Version:
+ 0,8

### Mods:
+ no mod

### Description:
+ The game crashes if inventory item is moved to container by right-clicking.

### Steps to reproduce:
+ If you open up an inventory of a container (red ones near the huron-container) and try to move an item in your inventory to the container by right-clicking, then the game crashes.

### Where did the issue occur?
+ Multiplayer- Testserver

**Comment by simon84** [comment]
Tested and fixed!
