### ISSUE TITLE
Heavy-Ammobox Nato

### ISSUE THREAD

**Issue by CptPopeye** [drakelinglabs/projectrealityarma3#293]
### ArmA3 Version:
+ 1.62

### PRA3 Version:
+ 0.8

### Mods:
+/

### Description:
+ Heavy ammo box contains RGP missels note the PCLM missels

### Steps to reproduce:
+ /

### Where did the issue occur?
+ Playtest (3ß.07.2016)

### RPT log file:
+ 
+

**Comment by simon84** [comment]
fixed with ee6afb6
