### ISSUE TITLE
Rewrite FOBs

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#295]

**Comment by Hoegnison** [comment]
#269

**Comment by simon84** [comment]
1. We need a FOB box, which is draggable.
2. After transporting of the FOB box to a appropiate position, deploy the FOB -> then a bunker (configurable object) is spawned. 
3. All Objects, which are stored into the FOB crate should be available in a crate nearby.
4. The bunker is the FOB object, which can be destroyed by the enemy (would be nice, if this is only possible with a satchel charge or other explosives).
