### ISSUE TITLE
How Should The Ticketsystem Work?

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#30]
As the wiki has only a little information about the ticketsystem, we should discuss how it should work in our first iteration.

**Comment by simon84** [comment]
Are there any news about it?

**Comment by Hoegnison** [comment]
Indeed. I will add them in a few hours, I am on a rush right now.

**Comment by Hoegnison** [comment]
So we have a lot of freedom about this. The initial idea is to use some ideas of PR.

-You lose 30 tickets, when you have lost a flag
-You lose tickets when a vehicle explodes. Ticket amount depending on vehicle
-You lose tickets in a steady flow when your last flag is captured by the enemy. This is called the ticket bleed
- You lose tickets when a player goes down and/or when he respawns.

Last thing is a design decision, but I guess it shoud have an effect on tickets, when a player goes down and not only when he hits the respawn button. What do you guys think about this point?

**Comment by jokoho48** [comment]
currently stuck on the implementation. try to finish i tomorrow

**Comment by jokoho48** [comment]
Done
