### ISSUE TITLE
Respawn timer resets for every recieved bullet

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#342]
Strange bug in the medic system. Accures when a player gets hit by multiple bullets after his death. 
Respawn timer resets serveral times after that.

**Comment by simon84** [comment]
Could not reproduce. In my tests, the bleeding rate increases for each bullet and the blood level decreases continuously.

**Comment by Hoegnison** [comment]
Do you have tested the double tap?

**Comment by netfusion** [comment]
afaik the issue did not occur in the last playtest

**Comment by simon84** [comment]
Now I understand the issue. The respawn timer in the respawn screen resets (or the respawnscreen itself comes up multiple times) when the dead player got shot. This was an issue due to the management of the damag event, which was fixed.
