### ISSUE TITLE
Discussion And Ideas About First FOB Implementation

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#35]
I think it would be great to  have a simple system for deploying FOBs in the first prototype.
The idea BD had, was to take a item/backpack/object which you can transport and use it to deploy a FOB. 
Using a vehicle like a special truck is not that cool I guess. When I am right in NetFusions AME was a possibility to add actions to classes, that could be a easy solution right?

**Comment by jokoho48** [comment]
Move to V0.2 because its not come in V0.1
