### ISSUE TITLE
Player marker on the map needs to be highlighted

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#358]
By now you have issues to find yourself on the map, especially if you are not sl or medic.

**Comment by TomNedry** [comment]
Player marker isn't highlighted. It should be some different color and/or shape. See [screenshot](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161108214623_1.jpg)...

**Comment by jokoho48** [comment]
did you tested it on the DeploymentRework Branch? there is currently the fix pushed

**Comment by TomNedry** [comment]
Tested & good. Player marker has color "white" now.
