### ISSUE TITLE
Think about how to restrict fob crates

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#359]
At least a temp. solution for 0.14+

**Comment by filipbasara** [comment]
I'd suggest restricting it by distance like PR and Squad do it. 400-500 meters from FOB to FOB.
Also, if we have "level bounds" this will naturally create a maximum FOB count depending on the size of the map which I think is a pretty self-explaining system. Bigger playable area, more FOBs.

**Comment by Hoegnison** [comment]
We couldnt meet the timeline and will add restrictions for requesting assets during the next iterations.

**Comment by Bluedrake42** [comment]
Yeah honestly the distance limitation seems like the most reasonable solution here.
