### ISSUE TITLE
Medic should be able to see wounded squadmates

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#360]
We should have a visible UI elemtn for medics, that marks wounded squadmates.

**Comment by TomNedry** [comment]
It should be distinguished between "wounded" and "unconscious".

**Comment by simon84** [comment]
3d Icons added. Next work: Map Icons

**Comment by pwilkutowski** [comment]
Tested on current 0.14.0.1800

 - The 3d icons are working fine, fixed
 - The 2d map icons are missing, reopen needs additional work

**Comment by jokoho48** [comment]
in the last update BI removed massiv amount of Icons from the Data what mean we need to research many icons
maybe more of a new task i would close this and we would need to find any icon that is missing and open a new issue

**Comment by jokoho48** [comment]
#463
