### ISSUE TITLE
Dead dead?

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#362]
When is a player dead dead so he has to respawn? Does it kill squad cohision? Which circumstances you need to be dead dead ?

DISCUSS!

**Comment by netfusion** [comment]
I like the idea.
At the moment its easy to wait at an unconscious enemy for enemies who want to revive him. This would add another state so its harder to determine wether an hit enemy is dead or unconscious.
On the other hand its hard to explain to the player why he can not be revived. The reason should be 
easy to understand and visible.

**Comment by filipbasara** [comment]
In my opinion a solid headshot should set the player to a dead state where he is forced to respawn. Getting into the state of incapacity should only occur when a certain health or damage value has been reached. Players who are incapacitated should not be forced to respawn when they're shot afterwards. So the mechanic off finishing off a player should not be present.
