### ISSUE TITLE
Sometimes people do not get the revive action

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#363]
### ArmA3 Version:
+Launcher version: 1.5.138680

Game version: 1.64.138732

Branch: main / beta branch not specified

### PRA3 Version:
+ 0.12

### Mods:
-

### Description:
Sometimes I was not able to revive people, because I could not get the revive action. Squad mates sometimes experienced the same issues, though the respawn worked in most of the cases.

### Steps to reproduce:
+ Appears randomly for me

### Where did the issue occur?
+ Dedicated

**Comment by simon84** [comment]
fixed
