### ISSUE TITLE
Mutex deadlock

### ISSUE THREAD

**Issue by simon84** [drakelinglabs/projectrealityarma3#37]
The mutex system has a problem with dead locks. When the client disconnects after he requested the token, the token is gone forever yielding to a dead lock. Maybe the prior pure server based approach of accessing global variables is more fail safe.

**Comment by jokoho48** [comment]
still not fixed onPlayerDisconnected only gets triggerd if a player leave the server but if the player still is in the lobby we have still a deadlock

**Comment by netfusion** [comment]
tested it and confirm that it fires when player goes to lobby

**Comment by jokoho48** [comment]
fixed
