### ISSUE TITLE
fix dat Loadout 

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#373]
- [x] Sniper have Wrong Uniform
- [x]  Sniper have Wrong Ammo
- [x] Nato Crewman have CSAT Uniform
- [x] Logistic Squad No Kits

**Comment by filipbasara** [comment]
We should discuss Kits in general. Maybe worth a revamp @Hoegnison ?

**Comment by Hoegnison** [comment]
We could do. As I am on leave during WE we could do it via phone if you want ;) @filipbasara 
@jokoho48 is logistic squad really needed atm?

**Comment by filipbasara** [comment]
No we got rid of them in all missions right now
