### ISSUE TITLE
Missing revive action on medic after medic gots revived itself

### ISSUE THREAD

**Issue by TomNedry** [drakelinglabs/projectrealityarma3#380]
### PRA3 Version:

Playtest 22oct16
### Description:
- Missing revive action on medic after medic gots revived itself.
- Lasts till respawn
### Steps to reproduce:
- Medic get shot -> unconscious
- Medic gets dragged and afterwards revived by non-medic
- No revive action (icon) while pointing on unconscious player

**Comment by jokoho48** [comment]
maybe player fault we currently can not reproduce it.

**Comment by TomNedry** [comment]
Although i reported this, i wasn't able to reproduce it.
