### ISSUE TITLE
Write a FAQ to prevent the same questions over and over again.

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#388]

**Comment by litrax** [comment]
In which form should we do this (wiki, pdf, ...)?
I mean it depends on where we wanna put this (wiki, discord, website, ...)?
My idea: First create the content here in the wiki and then put it on the website when it's ready...

What also bothers me: How can we manage the discord people to read the FAQ?
Writing a FAQ here will not stop the people on the discord to ask the same questions over and over again...
