### ISSUE TITLE
Crewman has no Overall

### ISSUE THREAD

**Issue by Montiemedia** [drakelinglabs/projectrealityarma3#391]
Version from 2016-31-10 09:00 PM with Console CMD ["Crewman"] call PRA3_Kit_fnc_applyKit; the Crewman hast no Uniform/Overall! This variable I start local and Global!

**Comment by netfusion** [comment]
Which faction did you play? NATO, CSAT or AAF?

**Comment by TomNedry** [comment]
Tested on NATO & CSAT. Issue occured on NATO only...

**Comment by jokoho48** [comment]
should be fixed. i accidentally used the wrong classname

**Comment by TomNedry** [comment]
Tested and works as intended.
