### ISSUE TITLE
Tank Crew Role Selection

### ISSUE THREAD

**Issue by Montiemedia** [drakelinglabs/projectrealityarma3#392]
If you Crewman, you couldn´t change Slot position from TankCommander or Gunner to Driver. If you´re out of the tank, you can slot in as Tank driver. From a players point of view, it´s not logical.

**Comment by TomNedry** [comment]
In PR:BF2 you can operate the assets with a single person. As you probably know there is a "switch timer" which creates an artificial delay, so you need about 30 seconds ([see PR:BF2 Manual for v1.3](http://www.realitymod.com/manual/pr_manual.pdf)) to switch between positions in tanks and similar vehicles and a shorter time period to switch such positions in "light assets" (e.g. Humvee). This is to prevent "alone wolf" behaviour...

Although it's a game design descision, i agree with Montie that from a players point of view it's not logical that a gunner or a commander position can't be manned by any player with crew-kit without a driver being in the vehicle. To prevent "alone wolfs" please see the paragraph above...

**Comment by TomNedry** [comment]
**Behaviour is**: Crew-kit mandatory for driver, gunner and commander. Gunner and commander can be manned while a player is on the driver position only. Gunner and commander stay on position while the driver gets out.
After consulting NetFusion and jokoho48 thats intended...

Tested & Good!
