### ISSUE TITLE
Unloading is possible inside vehicles

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#416]
### ArmA3 Version:
+ Launcher version: 1.5.138680

Game version: 1.64.138732

Branch: main / beta branch not specified

### PRA3 Version:
+ 0.13

### Mods:
+ none

### Description:
+ During platest on 04.11.16 Bluedrake was able to unload a crate while he was sitting in a helicopter. This just instantly destroyed the vehicle. Needs to be fixed asap. 

### Steps to reproduce:
+ load crates in a vehicle. enter as passenger. try to unload.

### Where did the issue occur?
+ Dedicated

### RPT log file:
-

**Comment by TomNedry** [comment]
Is reproducible!

It depends on the player position within the vehicle, as there seems to be no defined "drop/unload" points.

**Test-cases:**
a) Unloading as pilot in UH-80 destroys the vehicle instantly. Unloading as 1st passenger moves the UH-80 a small amount to the left, the crate is then very near to the right side of the vehicle.

b) Unloading as 1st passenger in the UH-67 drops the crate within(!) the bottom hull of the helicopter, which is not visible from outside (so not on the ground) and barely from inside, but without damaging the vehicle. Unloading as pilot drops the crate at the right side, a meter away from the cockpit.

c) Unloading as pilot from the Mi-290 damages the "sling" part of the vehicles (shown in the damage status), but the crate drops to the left a meter away from the cockpit.

**Comment by jokoho48** [comment]
but Now :D

**Comment by TomNedry** [comment]
Unload from inside a vehicle isn't possible anymore, but one get a "Error No Notification Text" instead of the correct notification...

**Comment by jokoho48** [comment]
now i fixed the text

**Comment by TomNedry** [comment]
Text is shown, but is too long... See [screenshot](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161107210031_1.jpg).

**Comment by jokoho48** [comment]
not Importent. #closed
