### ISSUE TITLE
Pilots should not be able to create FOBs

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#417]
It is pretty op to fly behind enemy lines and create a fob. Needs to be discussed.

**Comment by Hoegnison** [comment]
How do we fix this guys? Any ideas? I think just flying behind enemy lines and placing a fob is absolutly op.

**Comment by jokoho48** [comment]
i think we should delay this currently there is no easy was to fix this and on my point of view this is not that overpowered because a Helicopter is very loud and big

**Comment by litrax** [comment]
If I can make a suggestion: FOBs, in my opinion, should only be setup by a Rifle Squad Leader.

**Comment by netfusion** [comment]
i think mitsus idea is the best one

**Comment by Hoegnison** [comment]
is that easy to implement? We could make it a configurable value in the squad conf...
