### ISSUE TITLE
Finish deployment management

### ISSUE THREAD

**Issue by netfusion** [drakelinglabs/projectrealityarma3#42]
- [ ] ~~Marker for rallypoints~~

**Comment by simon84** [comment]
We should consider a server side group/squad Management, where we can register groups upon creation. Maybe we can use a namespace for each group, where we can store the group object and all objects or properties for this group. A reference of this namespace, can than be stored into an array to be able to iterate through all groups. A garbage collector process can through out all abandoned groups.

**Comment by netfusion** [comment]
Rest in #46
