### ISSUE TITLE
Loading/unloading double action menu entry on "HEMTT Transport (Covered)"

### ISSUE THREAD

**Issue by TomNedry** [drakelinglabs/projectrealityarma3#425]
### ArmA3 Version:
+ 1.64.138732

### PRA3 Version:
+ 07nov2120A16

### Mods:
+ None

### Description:
While [loading](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161107210120_1.jpg) / [unloading ](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161107210127_1.jpg) a logistic item into "HEMTT Transport (Covered)" there is a double action menu entry.

### Steps to reproduce:
+ Create Squad, join, keep Rifleman-kit
+ Spawn, go over to cargo area
+ Drag cargo to "HEMTT Transport (Covered)" => Double entry to load

### Where did the issue occur?
+ Dedicated

**Comment by jokoho48** [comment]
should be fixed in CLib Master

**Comment by TomNedry** [comment]
Tested & good!
