### ISSUE TITLE
Two squadleader in one squad, after leaving squad A and joining squad B

### ISSUE THREAD

**Issue by TomNedry** [drakelinglabs/projectrealityarma3#433]
### ArmA3 Version:
+ 1.64.138732

### PRA3 Version:
+ 08nov2135A16

### Mods:
+ None

### Description:
+ After leaving my squad as squadleader (last one left) and joining another squad lets keep me the squadleader-kit.

### Steps to reproduce:
+ Be last one left in squad A with squadleader-kit
+ Leave squad by clicking the "join" button on squad B, where allready a player with squadleader-kit is.
+ There two player with squadleader-kit in one squad ([screenshot](https://www.airpressuretendency.net/pra3_qa_3jdurhtdx997sk/20161108213409_1.jpg)).

### Where did the issue occur?
+ Dedicated

### RPT log file:
+ Add a link ([pastebin](http://pastebin.com/)) to the client and/or server RPT file.
+ You do not know where you can find your RPT? Find the answer [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by netfusion** [comment]
This is intended behavior because the kit can not change while a player is alive.

**Comment by TomNedry** [comment]
OK & closed
