### ISSUE TITLE
Re-spawn on map position 0:0:0 (player lands in left lower corner of map)

### ISSUE THREAD

**Issue by pwilkutowski** [drakelinglabs/projectrealityarma3#452]
### ArmA3 Version:
Launcher version: 1.5.138680
Game version: 1.64.138732

### PRA3 Version:
+ 0.14

### Description:
Player gets re-spawned on lower left corner of map, most likely coordinates 0,0,0, this happen to me once and to players (had reports on this) on public test server.

Until now i cannot reproduce this, maybe related to FOB's (?)
In general seems like coordinates are lost somewhere in chain of re-spawn methods 

### Steps to reproduce:
N/A, relatively rare and random - happen on dev test server and on  public test server

### Where did the issue occur?
+ Dev test server
+ Public test server

This is essencially for QA to scout - i cannot get the reproduction steps but the issue is there

**Comment by Hoegnison** [comment]
scheduled

**Comment by jokoho48** [comment]
current Idea why this could happen is that the player request a respawn and the server delays it for a few frames and while that the respawn point gets delted and the player spawns at [0,0,0], basicly a small Mutex based issue but easy fixable with a function that checks if a rallypoint is still valid and if not than throw a notification

**Comment by pwilkutowski** [comment]
Looks like fixed - i didn't encountered this so far, but cannot test properly i don't have a far far away VPN :)
Tested with ping 600 and packet loss,
