### ISSUE TITLE
Add Dismantle FOB Action

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#454]

**Comment by jokoho48** [comment]
this is currently implemented but i am currently not sure if we just want to delete the FOB or if we want to place a "New FOB crate again"

**Comment by filipbasara** [comment]
All we need is an option to remove the FOB. Should take like 15-20 seconds to remove it I would suggest. Maybe also add a cooldown so you can't place a new FOB instanly.

**Comment by jokoho48** [comment]
the cooldown can be implementent in a later version. currently the time is 10 sec.

**Comment by pwilkutowski** [comment]
Seems to work ok, closing
