### ISSUE TITLE
Mission not ending on server side

### ISSUE THREAD

**Issue by pwilkutowski** [drakelinglabs/projectrealityarma3#456]
### ArmA3 Version:
1.64.138732

### PRA3 Version:
0.14 or... 0.13 ?
(GUI says server version 0.13.0.1512.. not sure if i should believe it :))

### Mods:
N/A

### Description:
This issue was present already, just don't see it on board so opening new one.
Essentially the mission does not end on server side, while it ends on the player side. As an effect new game starts with tickets and fobs from last started game

Since this was tested on dev server, I'm suspecting that the amount of time the public mission lasted (it took 2 hours or more) impacted this.

### Steps to reproduce:
 - start server play the game
 - Drop down the number of tickets bellow zero

### Where did the issue occur?
 - Public test server

### RPT log file:
no logs this was most likey server side

**Comment by jokoho48** [comment]
fixed on master

**Comment by pwilkutowski** [comment]
Seems to be fixed - i had normal reboots on test server, once pushed to public test we need to observe if this happens again
