### ISSUE TITLE
Recover Design Documents

### ISSUE THREAD

**Issue by Hoegnison** [drakelinglabs/projectrealityarma3#5]
Recover or rewrite the essential design documents and feature lists. Also maybe create a seperate feature list for the first "iteration" of the mod.

**Comment by Bluedrake42** [comment]
Currently working on this, eta an hour or two

**Comment by Bluedrake42** [comment]
This has now been completed: https://github.com/drakelinglabs/projectrealityarma3/wiki/Game-Design
