### ISSUE TITLE
Development/Playtesting Meeting

### ISSUE THREAD

**Issue by Bluedrake42** [drakelinglabs/projectrealityarma3#58]
Sven was interested in having a meeting to go over progress, and test development this week. Mark what time everyone would be most interested in having this, and we can schedule hopefully this week.

**Comment by Hoegnison** [comment]
I just recognized that I am short on time toworrow. So which time/ day would our devs prefer. I guess BadGuy has the least amount of free time, so I would like to hear what he is thinking.

**Comment by Bluedrake42** [comment]
That's fine, I can do whenever, just let me know and I can usually make it work

**Comment by simon84** [comment]
Hi, I'm on vacation until sunday evening. But feel free to meet. From sunday til friday I have free time.
