### ISSUE TITLE
Tab VS 4 Spaces

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#6]
Tab:
Pros:
 - Better for Later Compression in Compile Function(smaller trafic while loading function from server)

Cons:
 - Not Readable at Github and other Pages
 - Every Tool have different sizes of Tabs

4 Spaces:
Pros:
 - Readable at Github and Other Pages
 - Spaces have very simular sizes over tools

Cons:
 - Harder to Compress == Larger Trafic while function receiving

**Comment by Hoegnison** [comment]
TAB!

**Comment by simon84** [comment]
Does preprocesslinenumber not a compression of the Code?

**Comment by jokoho48** [comment]
no badly not

**Comment by simon84** [comment]
I like spaces. unfortunately arma has no regexp functions

**Comment by jokoho48** [comment]
but i think its good if we could write some kind of function that compresse the script and remove double spaces. new lines allready gets removed in the compile function

**Comment by netfusion** [comment]
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces
http://www.w3schools.com/js/js_conventions.asp
https://msdn.microsoft.com/de-de/library/ff926074.aspx
https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs

ich könnte hier noch tausend links posten...
**SPACES**

**Comment by Hoegnison** [comment]
Aight lets do spaces!

**Comment by jokoho48** [comment]
:+1:

**Comment by simon84** [comment]
So we can close the issue now.
